### ISSUE TITLE
[Bug]: Crude Oil is unobtainable

### ISSUE THREAD

**Issue by Nonokadono** [AllTheMods/All-the-mods-9-Sky#104]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

Due to there being only one biome in the overworld it is impossible to obtain crude oil. Either from pneumatic or industrial foregoing. You cannot Laser Drill, nore can you fish for an oily bee.

**Comment by Nonokadono** [comment]
An obvious fix would be to put the biome whitelist for the Laserdrill on "any"

**Comment by Bodadis** [comment]
No need to change the biome whitelist, I suggest do Ars Caelum: Ritual of Conjuring Island: Cascading. It makes a Warm Ocean biome, and in that biome you can use laser drills to get Crude Oil.

**Comment by 7eggert** [comment]
Please make a quest explaining it, I didn't find it out except by finding this issue

**Comment by TheBedrockMaster** [comment]
Should be mentioned in the PneumaticCraft quest chapter.

**Comment by 7eggert** [comment]
That chapter says "Hint: check the biome..." A good hint for the not-sky version.


I am doing the bees chapter ( oily bee) and looked at ars noveau because of this thread. There's no hint about the islands in that quest book chapter either. I didn't do pneumaticraft yet, just building what's necessary till now.

 I'm learning about the mods one by one, this pack is a good way to do that (thanks btw)
:-)

**Comment by TheBedrockMaster** [comment]
Strange, at some point it definitely explained how to get it in the sky, something might of happened between updates though assuming you’re on the latest release. Glad you’re enjoying the pack.
