### ISSUE TITLE
[Bug]: AE2 Cell Workbench - Unable to partition more than 1 item

### ISSUE THREAD

**Issue by kalisture** [AllTheMods/All-the-mods-9-Sky#121]
### Possible Fixes

No

### Modpack Version

1.0.1 & 1.0.2 curseforge

### What happened?

Whenever an additional item is attempted to be partitioned in a cell workbench, it clears the rest of the partitions.

I usually use ae2 in a mix of ways, including similar to functional storage/drawers as I find it more convenient and less laggy. This relies on partitioning, however after setting things up  I realise it's broken. I'm unable to fix it or find a workaround. There is a button that assigns partitions, but that doesn't seem to get all of the contents.

Unsure if it's just AE2 or caused by another mod/addition.

https://github.com/AllTheMods/ATM-9/assets/58401406/f2194998-1a57-43ef-a5d8-1107985054ad

### latest.log

 https://gist.github.com/kalisture/d8cc56924b0cd5c8192e9cbce5774f59

**Comment by kalisture** [comment]
Downgrading to 1.0.0 works for now

**Comment by logicallysound** [comment]
I have also seen this behavior. If you press the button that creates the partition based on what's already stored in the cell, it will add all of the items to the partition, even if it doesn't look like it in the cell workbench window. This is a bit vexing for me as I am trying to set up partitions which could include items I don't have yet, which can't be done because of this bug.

The alternative is to create the partition based on already-stored items and then re-partition the disk when you want to add new item types, which is a really tedious workaround. You end up having to take the disk out, clear the partition, add the new item(s), then put it back in the workbench to update the partition.

**Comment by kalisture** [comment]
I recall trying that, however found it didn't partition for all items functionally so I gave up and changed pack version.

**Comment by kalisture** [comment]
Still broken on 1.0.3

**Comment by Spectra9999** [comment]
Seems to be fixed on 1.0.4

**Comment by Pillgar** [comment]
I'm seeing this same bug in ATM9 - No Frills after updating to v1.14.
