### ISSUE TITLE
[Bug]: Induction Smelter only inserts Sand(Catalyst) in the top main slot. Not the bottom where it's supposed to go. 

### ISSUE THREAD

**Issue by Slamma33** [AllTheMods/All-the-mods-9-Sky#214]
### Possible Fixes

Yes

### Modpack Version

1.0.3

### What happened?

I'm trying to automate crafting apatite and it won't insert the catalyst through the RS exporter. The sand for the catalyst keeps on going in the main center slot and not the bottom slot. There doesn't seem to be a way to have 2 different inputs for the configuration.
![Capture](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/172237298/aad10723-4e7a-4d38-8dd5-f54f64480dbf)

**Comment by Hamredahl** [comment]
It will input to the correct slot if there is already sand in the catalyst slot, put one sand in there before connecting the RS exporter and you should be good. Pretty janky and probably prone to failure if your sand generation is slower than the induction smelter, but it works. I'd recommend using another catalyst instead, since they work without the janky.

I don't think this should be in the ATM git though, since it's an issue on Thermals side with the removal of being able to lock the catalyst slot, or a specific secondary input configuration. The recipe that creates this issue (hardened glass calls for sand in top slot) is also a "vanilla" Thermal recipe, not an ATM addition.

Cheers!
