### ISSUE TITLE
xycraft extractor not extracting dragon egg

### ISSUE THREAD

**Issue by Shadedstalker3** [AllTheMods/All-the-mods-9-Sky#6]
Xycraft extractor does not extract dragon eggs like it says in jei

**Comment by Kevin-Marsh** [comment]
I did some research. Though the preview is a little incorrect. Though it shows it as the extractor on top of the egg it should actually bee the egg on top of the extractor. Place a block two air blocks above whatever. Place the extractor against that block underneath it so that the extractor faces downwards, place a chest under the extractor. Then break the block and replace with an egg.

![2024-04-24_05 26 27](https://github.com/AllTheMods/All-the-mods-9-Sky/assets/9076964/cbc95520-24ab-42be-b886-7396ad81e7bf)
