### ISSUE TITLE
Standard ATM9 Questlines available

### ISSUE THREAD

**Issue by minomy13** [AllTheMods/All-the-mods-9-Sky#727]
### Possible Fixes

Yes

### Modpack Version

1.1.2

### What happened?

Since I downloaded the latest version the standard ATM9 Questlines for Allthemodium and Mystical Agriculture are available - but one can not complete them because some items are not craftable.

**Comment by nearbyttv** [comment]
same issue is this a quest line that wasnt meant to be added?

**Comment by bigdaddyslimtim** [comment]
Is this fixed yet or any way to get around it? I'm trying to 100% the modpack and I can't with all the quests that are unable to be completed.

**Comment by bobosmecher** [comment]
same issue here, is there a fix yet?

**Comment by stevohall** [comment]
This is the same issue ref: [Quests issues]: #710, the fix was to delete the below files

[c0rphan](https://github.com/c0rphan) added 2 commits [last month](https://github.com/AllTheMods/All-the-mods-9-Sky/pull/717#commits-pushed-8fc6649)
@c0rphan
[Delete config/ftbquests/quests/chapters/mystical_ag.snbt](https://github.com/AllTheMods/All-the-mods-9-Sky/pull/717/commits/8fc6649393a8cd21dd3d327b7dd287217c80d448)
8fc6649
@c0rphan
[Delete config/ftbquests/quests/chapters/allthemodium.snbt](https://github.com/AllTheMods/All-the-mods-9-Sky/pull/717/commits/9db926b312002f7b8b3b2a99620df66dbdbd04a1)

**Comment by StealthSnake21** [comment]
> This is the same issue ref: [Quests issues]: #710, the fix was to delete the below files
> 
> [c0rphan](https://github.com/c0rphan) added 2 commits [last month](https://github.com/AllTheMods/All-the-mods-9-Sky/pull/717#commits-pushed-8fc6649) @c0rphan [Delete config/ftbquests/quests/chapters/mystical_ag.snbt](https://github.com/AllTheMods/All-the-mods-9-Sky/pull/717/commits/8fc6649393a8cd21dd3d327b7dd287217c80d448) [8fc6649](https://github.com/AllTheMods/All-the-mods-9-Sky/commit/8fc6649393a8cd21dd3d327b7dd287217c80d448) @c0rphan [Delete config/ftbquests/quests/chapters/allthemodium.snbt](https://github.com/AllTheMods/All-the-mods-9-Sky/pull/717/commits/9db926b312002f7b8b3b2a99620df66dbdbd04a1)

That's a workaround, not a fix. If they plan to implement those quest lines, you are deleting things for no reason.

**Comment by c0rphan** [comment]
Those files add duplicated questlines that are already implemented in other
files. They seem to have been accidentally copied in from ATM9 (not in the
sky)

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/All-the-mods-9-Sky/issues/710
